stripe_subscription.settings:
  type: config_object
  label: 'Stripe Subscription settings'
  mapping:
    stripe_api_key:
      type: string
      label: 'Secret API Key'
    stripe_publishable_key:
      type: string
      label: 'Stripe Publishable Key'
    stripe_price_id:
      type: string
      label: 'Stripe Price ID'
    payment_form_role:
      type: string
      label: 'Payment Form Role'
    paid_user_role:
      type: string
      label: 'Paid User Role'